### PR TITLE
HDF5File now loads the library on creation

### PR DESCRIPTION
**Pull request by lbergelson**
This prevents errors where developers forgot to load the library manually.  It is still recommended to manually load the library in order to fail fast quickly and in a controlled way.

It was necessary to change HDF5File.OpenMode to keep a Supplier instead of an int, this is intended to delay classloading of H5 which will attempt and fail to load the native code on load.

### CODE REVIEW

**Comment by lbergelson** [comment]
Part of fixing https://github.com/broadinstitute/gatk-protected/issues/656

**Comment by LeeTL1220** [comment]
@lbergelson Do I care that the travis is failing?  Otherwise, looks good.  Thanks for putting the explanation comment in.

**Comment by lbergelson** [comment]
I don't think you care that it's failing in travis, but I'm confused about it.  Will debug.

**Comment by lbergelson** [comment]
It turned out there was some problem with travis osx builds.  Deleting the caches and rerunning fixed it.

**Pull request merged**
